#Esse é mais pra quando vc for usar um cloud provider o que nao será o caso pois vc tá no 
#linux e tá usando o minikube, socega o faicho ae

apiVersion: v1
kind: Service
metadata:
  name: svc-pod-loadbalancer-1
spec:
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 3000
  selector:
    app: primeiro-pod