apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports: 
    - port: 80
      #targetPort: 80 como é o mesmo numero, subtende-se que é a mesma porta
      nodePort: 30000
  selector:
    app: primeiro-pod